export const userDetails = [
  {
    name: "Onipe Theoderic Ohinoyi",
    position: "Fullstack Software Engineer",
    picture: "http://users.comnet.aalto.fi/oulasvir/4-boxed.png",
    skills_interest: [
      "software development",
      "team management",
      "graphic design",
      "mobile development",
      "ios development",
      "android development",
      "hardware engineering",
    ],
    proficient: ["English", "Spanish", "Yoruba", "Hausa"],
    technologies: [
      "Node",
      "Express",
      "Es6",
      "Javascript",
      "Ansible",
      "Terraform",
      "React Native",
      "Reactjs",
      "Nextjs",
      "Typescript",
      "Storybook UI",
      "Material UI",
      "Bootstrap",
      "SASS",
      "Docker",
      "Kubernetics",
      "MongoDB",
      "Mysql",
      "Postgres",
      "HTML5",
      "CSS3",
      "Redux",
      "Redux toolkit",
      "Context API",
      "Serverless",
      "AWS",
      "Ruby on Rails",
      "Watir",
    ],
    recommendation: 4,
    related_experience: [
      {
        position: "Mobile Developer",
        duration: "Aug 2016 - Nov 2016",
        company: "Jobberman",
      },
      {
        position: "Team Management",
        duration: "Feb 2017 - July 2018",
        company: "Google",
      },
      {
        position: "Frontend Engineer",
        duration: "Aug 2018 - October 2020",
        company: "Craiglist",
      },
    ],
  },
  {
    name: "John Paul",
    position: "Mobile Engineer",
    picture:
      "https://s3.amazonaws.com/37assets/svn/1024-original.1e9af38097008ef9573f03b03ef6f363219532f9.jpg",
    skills_interest: [
      "mobile development",
      "ios development",
      "android development",
    ],
    proficient: ["English"],
    technologies: ["swiftUI", "Java", "android", "React Native"],
    recommendation: 6,
    related_experience: [
      {
        position: "Mobile Developer",
        duration: "Feb 2015 - July 2016",
        company: "Amazon",
      },
      {
        position: "Ios developer",
        duration: "Aug 2016 - Nov 2016",
        company: "Instagram",
      },
      {
        position: "Game engineering",
        duration: "Feb 2017 - July 2018",
        company: "Google",
      },
    ],
  },
  {
    name: "Paul Stone",
    position: "Backend Engineer",
    picture: "https://cxl.com/wp-content/uploads/2016/03/nate_munger.png",
    skills_interest: ["software development", "backend engineer"],
    proficient: ["English", "Spanish", "Yoruba", "Hausa"],
    technologies: [
      "Node",
      "Express",
      "Es6",
      "Javascript",
      "Ansible",
      "Terraform",
      "Typescript",
      "Docker",
      "Kubernetics",
      "MongoDB",
      "Mysql",
      "Postgres",
      "Serverless",
      "AWS",
      "Ruby on Rails",
    ],
    recommendation: 2,
    related_experience: [
      {
        position: "Backend Engineer",
        duration: "Feb 2015 - July 2016",
        company: "Airbnb",
      },
      {
        position: "Mobile Developer",
        duration: "Aug 2016 - Nov 2016",
        company: "Facebook",
      },

      {
        position: "Frontend Engineer",
        duration: "Aug 2018 - October 2020",
        company: "Netflix",
      },
    ],
  },
  {
    name: "Barry Beckett",
    position: "Fullstack Software Engineer",
    picture:
      "https://medical-technology.nridigital.com/medical-technology/medical_technology_may19/is_software_a_blind_spot_for_the_medical_device_industry/391842/Sam_pic___credit_VivaLNK.512_0_1.png",
    skills_interest: [
      "software development",
      "team management",
      "mobile development",
    ],
    proficient: ["English", "Spanish", "Yoruba", "Hausa"],
    technologies: [
      "Node",
      "Express",
      "Es6",
      "Javascript",
      "React Native",
      "Reactjs",
      "Nextjs",
      "Typescript",
      "Storybook UI",
      "Material UI",
      "Bootstrap",
      "SASS",
      "MongoDB",
      "Mysql",
      "Postgres",
      "HTML5",
      "CSS3",
      "Redux",
      "Redux toolkit",
      "Context API",
      "Serverless",
      "AWS",
      "Ruby on Rails",
    ],
    recommendation: 5,
    related_experience: [
      {
        position: "Senior Software Engineer",
        duration: "Feb 2015 - July 2016",
        company: "Amazon",
      },
      {
        position: "Mobile Developer",
        duration: "Aug 2016 - Nov 2016",
        company: "Google",
      },
      {
        position: "Team Management",
        duration: "Feb 2017 - July 2018",
        company: "Facebook",
      },
    ],
  },
];
